# Generated by Django 2.0.9 on 2019-03-22 01:29

from django.db import migrations, models
import uploads.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160801_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='copilot_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='copilot_nickname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='pilot_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='pilot_nickname',
            field=models.CharField(default='bubba', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='replay',
            field=models.FileField(blank=True, null=True, upload_to=uploads.core.models.replay_directory_path),
        ),
        migrations.AddField(
            model_name='document',
            name='skin',
            field=models.FileField(blank=True, null=True, upload_to=uploads.core.models.skin_directory_path),
        ),
    ]
