# Generated by Django 2.0.9 on 2019-03-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190322_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='copilot_name',
            field=models.CharField(blank=True, help_text='Your name might be visible in the video!', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='pilot_name',
            field=models.CharField(blank=True, help_text='Your name might be visible in the video!', max_length=200),
        ),
    ]
