# Generated by Django 2.0.9 on 2019-03-22 08:21

from django.db import migrations, models
import uploads.core.models
import uploads.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_gdpr_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='copilot_name',
            field=models.CharField(blank=True, help_text='This name might be included on videos and other resources online, make sure you read the terms.', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='pilot_name',
            field=models.CharField(blank=True, help_text='This name might be included on videos and other resources online, make sure you read the terms.', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='replay',
            field=models.FileField(blank=True, help_text='This is the replay file, just put here one file, no compressed.', null=True, upload_to=uploads.core.models.replay_directory_path, validators=[uploads.core.validators.validate_file_size, uploads.core.validators.validate_replay_file]),
        ),
        migrations.AlterField(
            model_name='document',
            name='skin',
            field=models.FileField(blank=True, help_text='This is the skin of the car, please upload a compressed file with only the files you edited!', null=True, upload_to=uploads.core.models.skin_directory_path, validators=[uploads.core.validators.validate_file_size]),
        ),
    ]
