# Generated by Django 2.0.9 on 2019-03-22 09:39

from django.db import migrations, models
import uploads.core.models
import uploads.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190322_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='copilot_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='pilot_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='replay',
            field=models.FileField(blank=True, null=True, upload_to=uploads.core.models.replay_directory_path, validators=[uploads.core.validators.validate_file_size, uploads.core.validators.validate_replay_file]),
        ),
        migrations.AlterField(
            model_name='document',
            name='skin',
            field=models.FileField(blank=True, null=True, upload_to=uploads.core.models.skin_directory_path, validators=[uploads.core.validators.validate_file_size]),
        ),
    ]
