# Generated by Django 2.0.13 on 2019-03-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190322_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='gdpr_accept',
            field=models.BooleanField(),
        ),
    ]
