# Generated by Django 2.0.13 on 2019-03-31 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_document_replays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('uploaded_at', 'pilot_name')},
        ),
    ]
