# Generated by Django 2.0.13 on 2019-07-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190331_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='edited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
