# Generated by Django 2.0.13 on 2019-07-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190711_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-uploaded_at', 'pilot_name')},
        ),
    ]
