# Generated by Django 2.0.13 on 2019-07-12 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_auto_20190711_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('pilot_name', models.CharField(blank=True, max_length=200)),
                ('pilot_nickname', models.CharField(blank=True, max_length=200)),
                ('copilot_name', models.CharField(blank=True, max_length=200)),
                ('copilot_nickname', models.CharField(blank=True, max_length=200)),
                ('rally', models.CharField(blank=True, max_length=200)),
                ('track', models.CharField(max_length=200)),
                ('stage_number', models.CharField(blank=True, max_length=200)),
                ('car', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('time', models.CharField(blank=True, max_length=200)),
                ('youtube_url', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('replay', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Replay')),
            ],
        ),
    ]
