# Generated by Django 2.0.13 on 2019-07-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20190712_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='youtube_url',
            new_name='youtube_id',
        ),
    ]
