# Generated by Django 2.0.13 on 2019-07-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20190712_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='copilot_name',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='copilot_nickname',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='pilot_name',
        ),
        migrations.AddField(
            model_name='performance',
            name='team',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
