# Generated by Django 2.0.13 on 2019-07-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20190712_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
