# Generated by Django 2.0.13 on 2019-07-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_performance_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='pilot_nickname',
            new_name='pilot',
        ),
    ]
