# Generated by Django 2.0.13 on 2019-08-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20190715_0559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ('-featured', '-uploaded_at')},
        ),
    ]
